#!/bin/bash
set -o xtrace
RAILS_ENV=test bundle install --path vendor/bundle --binstubs bin/stubs --without ""
RAILS_ENV=test bundle exec rake
RAILS_ENV=test bundle exec rake assets:precompile
RAILS_ENV=test bundle exec jasmine-headless-webkit
