#!/usr/bin/env bash
#
# Install Ruby gems as needed.
#
#   * Check the `gem list` to see if the gem is already installed.
#
#   * If so, then skip it, otherwise install it.
#
# Example:
#
#    gem-install-fast rails
#
# Example using STDIN:
#
#    echo rails | gem-install-fast
#
# This script can get the gem name from the command line,
# or can process STDIN lines to install many gems at once.
#
# We filter STDIN by selecting each line that starts with
# with any whitespace then any alphanumeric character;
# in practice this filters out comments and blank lines.

# This script doesn't do anything about gem versions;
# this topic can be a good area for future upgrades.
#
# How this script works line by line:
#
#   1. Choose the input as either STDIN or $1
#   2. Select each input line that has leading text, and match the first word.
#   3. Compare each line to the existing gem list line(s).
#   4. Install the gems
#
([ $# -eq 0 ] && "cat" || echo "$1") |
sed -n 's/^[[:blank:]]*\([[:alnum:]][^ ]*\)/\1/p' |
sort -u | comm -23 - <(gem list | awk '{print $1}') |
xargs -I{} gem install "{}"
