#!/usr/bin/env ruby
#
# Ruby script to install a gem if it's needed.
#
# If the gem is missing, then install it.
# If the gem is present, then do nothing.
#
# This command calls "gem list" to find what's installed.
#
# Example:
#
#    gem-install-fast bdoc
#
# Example of multiple gems:
#
#    gem-install-fast bdoc rdoc sdoc
#
# This command can also processes STDIN:
#
#    cat gems.txt | gem-install-fast
#
names = (ARGV.size > 0) ? ARGV  : STDIN

gem_list = `gem list`.lines.map{|line| line.chomp}
gem_lookup = Hash[gem_list.map{|line| [line.sub(/ .*/,''), true]}]

names.each{|name|
  if gem_lookup[name]
    puts "#{name} [installed]" 
  else
    puts "#{name} [installing]" 
    `gem install #{name}`
  end
}




